services:
  app:
    build:
      context: airportapi/
    ports:
      - "8000:8000"
    volumes:
      - ./airportapi/src:/src
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=pass
    depends_on:
      - db
    networks:
      - backend
    container_name: app

  scanner:
    build:
      context: metarscanner/
    restart: always
    environment:
      - API_HOST=app
      - API_PORT=8000
    depends_on:
      - app
    networks:
      - backend
    container_name: scanner

  db:
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    networks:
      - backend
    container_name: db
    

networks:
  backend:
